### ISSUE TITLE
[Contato] - Informações {1}

### ISSUE THREAD

**Issue by Tiago-Marques** [Tiago-Marques/transneno#18]
ESTIMATIVA: 1h

- [x] Telefone (?)

- [x] Facebook

- [x] Linkedin

**Comment by Tiago-Marques** [comment]
Bloqueado;
Não temos Telefone atualizado, Facebook, Linkedin.

**Comment by joicefdantas** [comment]
Temos resolvido: Telefone (linkedin e facebook ainda vai ser enviado)

**Comment by joicefdantas** [comment]
Foram atualizados os telefones e colocados os links de Linkedin e Facebook, faltando apenas o link correto que provavelmente será passado pelo cliente somente em Janeiro
