### ISSUE TITLE
[Geral] - Favicon {1}

### ISSUE THREAD

**Issue by Tiago-Marques** [Tiago-Marques/transneno#19]
ESTIMATIVA: 1h

([https://realfavicongenerator.net/])
Com suporte para devices.

**Comment by Tiago-Marques** [comment]
Bloqueado; 
Falta a imagens atualizadas;

**Comment by joicefdantas** [comment]
The favicon image was changed by client

**Comment by joicefdantas** [comment]
new favicon added.
