### ISSUE TITLE
[Página] - Home

### ISSUE THREAD

**Issue by Tiago-Marques** [Tiago-Marques/transneno#4]
- #5 [Home] - Header {2} 

- #6 [Home] - Banner {3}

- #7 [Home] - Seção Bem vindo {1}

- #8 [Home] - Seção Modalidades de transportes {1}

- #9 [Home] - Seção Valores {1}

- #10 [Home] - Footer {1} 

- #21 [Home] - Definição de imagens {2}

**Comment by joicefdantas** [comment]
Waiting for the blocks.
