### ISSUE TITLE
[Home] - Header {2}

### ISSUE THREAD

**Issue by Tiago-Marques** [Tiago-Marques/transneno#5]
ESTIMATIVA: 2h

- [x] Logo

- [x] Menu

- [ ] Telefone (?)

**Comment by Tiago-Marques** [comment]
Bloqueado; 
Faltando a definição de menu para Serviços

**Comment by joicefdantas** [comment]
Temos resolvido: logo e telefone.
Faltando apenas a definição do menu.

**Comment by Tiago-Marques** [comment]
Os serviços executados são os seguintes:
 
-Coletas e entregas Fracionadas ( foco auto peças).
-Coletas e entregas expressas ( feitas no mesmo dia ou até 24h.) Entrega
 
* Pedidos feitos entre 8h00 e 11h00, serão entregues até às 18h00 do mesmo dia e os feitos entre 12h00 e 18h00  serão entregues no dia seguinte até ao meio dia.
 
-Transporte de cargas programado.
-Transporte de documentos e malotes.
 
Gostaria também de colocar as cidades que atendemos, pois isso é importante então estou enviando a rota em anexo.(rotas 2017).
 
Enviei um documento como proposta  para você avaliar se consegue utilizar alguma coisa do texto.
 
Os nossos  parceiros principais são:
 
Distribuidora Pacaembu auto peças.
Distribuidora Furacão
Distribuidora DPK
Distribuidora SK
Distribuidora Rolemar
Distribuidora Sama
Distribuidora Car-Central
Distribuidora Pellegrino
Distribuidora Cobra
Distribuidora CCMX Lubrificantes
Distribuidora Bigua
Distribuidora Real moto peças
Distribuidora Gimenes
Distribuidora Haifer
Distribuidora Autopec
Distribuidora Paccini.
